package com.revio.server.core.error

enum class AuthErrorCode {
    ACCESS_TOKEN_EXPIRED,
    ACCESS_TOKEN_INVALID,
    ACCESS_TOKEN_MISSING,
    REFRESH_TOKEN_INVALID,
    REFRESH_TOKEN_EXPIRED,
    REFRESH_TOKEN_REUSED,
    REFRESH_TOKEN_CONSUMED,
    SESSION_REVOKED,
    SIGNED_IN_ON_ANOTHER_DEVICE,
    INVALID_CREDENTIALS,
    PROVIDER_MISMATCH,
    INVALID_GOOGLE_TOKEN,
    EMAIL_TAKEN,
    WEAK_PASSWORD,
    VALIDATION_ERROR,
    USERNAME_TAKEN,
    PROFILE_EXISTS,
    ONBOARDING_REQUIRED,
    ACCOUNT_NOT_FOUND,
    ACCOUNT_DELETED,
    INVALID_CURRENT_PASSWORD,
    PROVIDER_NOT_REGULAR,
    USERNAME_CONFIRMATION_MISMATCH,
    ACCOUNT_SUSPENDED
}
